CREATE TABLE "daaf_bot_daily_margin" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"snapshot_date" date NOT NULL,
	"slug_id" text NOT NULL,
	"bot_name" text NOT NULL,
	"attributed_revenue" numeric(12, 2) DEFAULT '0' NOT NULL,
	"attributed_order_count" integer DEFAULT 0 NOT NULL,
	"avg_order_amount" numeric(10, 2),
	"paid_user_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"paid_user_task_count" integer DEFAULT 0 NOT NULL,
	"free_user_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"free_user_task_count" integer DEFAULT 0 NOT NULL,
	"total_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_task_count" integer DEFAULT 0 NOT NULL,
	"gross_profit" numeric(12, 2) DEFAULT '0' NOT NULL,
	"gross_margin_pct" numeric(7, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_bot_daily_margin" UNIQUE("snapshot_date","slug_id")
);
--> statement-breakpoint
CREATE TABLE "daaf_bot_revenue_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"snapshot_date" date NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"period_end" timestamp with time zone NOT NULL,
	"slug_id" text NOT NULL,
	"bot_name" text NOT NULL,
	"bot_id" integer,
	"task_count" integer DEFAULT 0 NOT NULL,
	"unique_users" integer DEFAULT 0 NOT NULL,
	"paid_user_tasks" integer DEFAULT 0 NOT NULL,
	"free_user_tasks" integer DEFAULT 0 NOT NULL,
	"paid_user_percentage" numeric(5, 2),
	"revenue_proportional" numeric(12, 2) DEFAULT '0' NOT NULL,
	"revenue_last_touch" numeric(12, 2) DEFAULT '0' NOT NULL,
	"revenue_last_touch_optimized" numeric(12, 2) DEFAULT '0' NOT NULL,
	"energy_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"paid_user_energy" numeric(12, 2) DEFAULT '0' NOT NULL,
	"free_user_energy" numeric(12, 2) DEFAULT '0' NOT NULL,
	"revenue_cost_ratio" numeric(8, 2),
	"days_online" integer,
	"first_task_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_snapshot_slug" UNIQUE("snapshot_date","slug_id")
);
--> statement-breakpoint
CREATE TABLE "daaf_cost_daily_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"snapshot_date" date NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"period_end" timestamp with time zone NOT NULL,
	"total_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"paid_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost_pct" numeric(5, 2),
	"total_tasks" integer DEFAULT 0 NOT NULL,
	"total_users" integer DEFAULT 0 NOT NULL,
	"temp_email_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"temp_email_users" integer DEFAULT 0 NOT NULL,
	"temp_email_tasks" integer DEFAULT 0 NOT NULL,
	"regular_email_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"regular_email_users" integer DEFAULT 0 NOT NULL,
	"regular_email_tasks" integer DEFAULT 0 NOT NULL,
	"deleted_user_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"deleted_user_count" integer DEFAULT 0 NOT NULL,
	"deleted_user_tasks" integer DEFAULT 0 NOT NULL,
	"visitor_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"visitor_count" integer DEFAULT 0 NOT NULL,
	"visitor_tasks" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "daaf_cost_daily_snapshots_snapshot_date_unique" UNIQUE("snapshot_date")
);
--> statement-breakpoint
CREATE TABLE "daaf_daily_margin_summary" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"snapshot_date" date NOT NULL,
	"paid_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost_regular_email" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost_temp_email" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost_gmail_alias" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost_deleted" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost_visitor" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"free_cost_pct" numeric(5, 2),
	"stripe_revenue" numeric(14, 2) DEFAULT '0' NOT NULL,
	"paypal_revenue" numeric(14, 2) DEFAULT '0' NOT NULL,
	"iap_revenue" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_revenue" numeric(14, 2) DEFAULT '0' NOT NULL,
	"gross_profit" numeric(14, 2) DEFAULT '0' NOT NULL,
	"gross_margin_pct" numeric(7, 2),
	"total_order_revenue" numeric(14, 2) DEFAULT '0' NOT NULL,
	"attributed_revenue" numeric(14, 2) DEFAULT '0' NOT NULL,
	"unattributed_revenue" numeric(14, 2) DEFAULT '0' NOT NULL,
	"attribution_coverage_pct" numeric(5, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "daaf_daily_margin_summary_snapshot_date_unique" UNIQUE("snapshot_date")
);
--> statement-breakpoint
CREATE TABLE "daaf_daily_summary_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"snapshot_date" date NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"period_end" timestamp with time zone NOT NULL,
	"total_tasks" integer DEFAULT 0 NOT NULL,
	"total_bots" integer DEFAULT 0 NOT NULL,
	"total_unique_users" integer DEFAULT 0 NOT NULL,
	"total_paying_users" integer DEFAULT 0 NOT NULL,
	"total_revenue_proportional" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_revenue_last_touch" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_revenue_last_touch_optimized" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_energy_cost" numeric(14, 2) DEFAULT '0' NOT NULL,
	"stripe_order_count" integer DEFAULT 0 NOT NULL,
	"paypal_order_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "daaf_daily_summary_snapshots_snapshot_date_unique" UNIQUE("snapshot_date")
);
--> statement-breakpoint
CREATE TABLE "daaf_free_cost_by_bot_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"snapshot_date" date NOT NULL,
	"slug_id" text NOT NULL,
	"bot_name" text NOT NULL,
	"free_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"free_tasks" integer DEFAULT 0 NOT NULL,
	"free_users" integer DEFAULT 0 NOT NULL,
	"cost_pct" numeric(5, 2),
	"rank" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_free_cost_bot_snapshot" UNIQUE("snapshot_date","slug_id")
);
